### ISSUE TITLE
Support archivedLogFilenamePattern

### ISSUE THREAD

**Issue by davidmc24** [wotifgroup/grails-lightweight-deploy#21]
From comments in the code, it looks like it currently isn't supported due to some bug in logback.  I'd like to see this bug identified and fixed, so that we can move forward with supporting this.

https://github.com/wotifgroup/grails-lightweight-deploy/blob/master/src/java/grails/plugin/lightweightdeploy/logging/FileLoggingConfiguration.java

**Comment by deverton** [comment]
I think we were hitting this issue http://jira.qos.ch/browse/LOGBACK-173 which hasn't been resolved yet. I'll have to dig a bit further to confirm though.

**Comment by davidmc24** [comment]
Even if the logback issue hasn't been addressed, I'd like to have the option of using this feature.  It's possible that not everyone hits the logback issue (which I think is quite likely, as I haven't encountered this on our dropwizard apps).  By adding support for configuration of archive/archivedLogFilenamePattern/archivedFileCount, users would have the option of using this feature, or not, at their discretion.  I prefer to stick to the same defaults as Dropwizard (which in this case would mean rolling enabled by default), but I'm okay with defaulting to it being disabled.
