### ISSUE TITLE
Extract launcher logic into a library

### ISSUE THREAD

**Issue by davidmc24** [wotifgroup/grails-lightweight-deploy#27]
Thanks for the great plugin.  Do you have any interest in having the launcher/config logic available as a stand-alone library?  If so, I'd be willing to help work towards splitting that out.  I have a Gradle-built (non-Grails) application that could use exactly this sort of launcher.

**Comment by davidmc24** [comment]
@deverton Any comments on this?

**Comment by deverton** [comment]
It might be worth just splitting this project up a bit to allow for a the launcher to be a separate module. Then the Grails startup would be a separate module that takes over from there. It's not something we'd use (we tend to use Dropwizard for everything else) but I don't see why not.

**Comment by davidmc24** [comment]
I tend to use DropWizard or Ratpack for most everything else... but I've got one WAR (JASIG CAS) that I'm overlaying and would still like the same launch experience.

**Comment by davidmc24** [comment]
No need to leave a ticket open here for this.  If I get the time to spin this up as a working separate module, I'll circle back and check if we want to sync up.
