### ISSUE TITLE
HealthCheckUtil doesn't work as expected for environments other than production and test

### ISSUE THREAD

**Issue by davidmc24** [wotifgroup/grails-lightweight-deploy#31]
When using the plugin to build a lightweight deploy for the "development" environment, or a custom environment (such as "staging"), the "test" health check registry is used, while I would expect it should use the health check registry from the servlet context.

**Comment by CrossfireCurt** [comment]
Hi! Wish I saw this issue hours ago - I have a "Development" environment configured... spent a while trying to figure out why I had two instances of HealthCheckRegistry. I suppose the work-around for now is to register all healthchecks with the production HealthCheckRegistry (HealthCheckUtil.getHealthCheckRegistry(Environment.PRODUCTION)).

**Comment by davidmc24** [comment]
Looks like this likely also applies to the MetricRegistry.

**Comment by CrossfireCurt** [comment]
I'd like to submit a pull request to fix this, but there's a comment in the code: "Not all test types properly bootstrap the servletContext as of Grails 2.2.3. Therefore, in test mode, use a consistent instance". I haven't done a lot of digging, but does anyone know if there's a way to test that a servletContext has been properly boostrapped?

**Comment by davidmc24** [comment]
I haven't been affected by the issue that the comment refers to, but I assume that it's stating that in some test phases/types, no servlet context has been set and `ServletContextHolder.servletContext` returns `null`.

If that's the case, I would think it would be sufficient to use the metrics registry in the servlet attribute if present, and use the fallback logic if either the servlet context is null or the attribute isn't present.

CC: @caps @aharwood

**Comment by aharwood** [comment]
I remember writing this comment but can't quite remember the issue. I vaguely remember that it was working with "grails test-app unit:" but not "grails test-app integration:", or maybe the other way around.  I think it was an open bug against grails at the time.

You could remove the code and see what breaks with a "grails test-app". It may even be that it's only fixed in more recent grails versions though.
