### ISSUE TITLE
Add support for compressed requests

### ISSUE THREAD

**Issue by davidmc24** [wotifgroup/grails-lightweight-deploy#38]
Dropwizard supports compressed request bodies using an extension of Jetty's GzipFilter.  It would be useful if this plugin could do likewise.

https://github.com/dropwizard/dropwizard/blob/2655ac703a0f6ddb4eae933a74dae3d12fde287f/dropwizard-jetty/src/main/java/io/dropwizard/jetty/BiDiGzipFilter.java

**Comment by deverton** [comment]
Cloused by #39
